version: '3.9'
services:
  jupyterhub:
    restart: always
    image: jupyterhub
    build: 
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./root:/root
      - ./home:/home
      - ./etc_host:/etc_host
      - ./cert:/cert
    shm_size: '48gb'
    ports:
      # host:container
      - 8000:22
      - 80:80
      - 443:443
    environment:
      # `pipenv` will create an environment in the working directory
      - PIPENV_VENV_IN_PROJECT=1
    deploy:
      resources:
        limits:
          # Limit is the maximun resource the container can have.
          # number of cores this container can use (can be 0.5 means half core)
          cpus: '6'
          # maximun RAM this container can use
          memory: '120G'
        reservations:
          # Reserves is a minimun resource the container will always have.
          # cpus: '4'
          # memory: '4G'
          devices:
            - driver: nvidia
              capabilities: [gpu]
