version: '3.9'
services:
  jupyterhub:
    restart: always
    image: jupyterhub
    build: 
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./root:/root
      - ./home:/home
      - ./etc_host:/etc_host
      - ./cert:/cert
    shm_size: '48gb'
    ports:
      # host:container
      - 8000:22
      - 80:80
      - 443:443
    environment:
      # `pipenv` will create an environment in the working directory
      - PIPENV_VENV_IN_PROJECT=1
    deploy:
      resources:
        limits:
          # Limit is the maximun resource the container can have.
          # number of cores this container can use (can be 0.5 means half core)
          cpus: '32'
          # maximun RAM this container can use
          memory: '120G'
        reservations:
          # Reserves is a minimun resource the container will always have.
          # cpus: '4'
          # memory: '4G'
          devices:
            - driver: nvidia
              # count: 1
              capabilities: [gpu]
  ldapadmin:
    image: ldapadmin
    build: 
      context: .
      dockerfile: ldapadmin.Dockerfile
    ports:
      - 2000:80
    volumes:
      - ./phpldapadmin:/var/www/html
  ldap:
    image: openldap
    build: 
      context: .
      dockerfile: openldap.Dockerfile
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_PORT_NUMBER: 389
      LDAP_ROOT: dc=brainlab
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD_FILE: /.ldappasswd
      # LDAP_ENABLE_TLS: "yes"
      # LDAP_LDAPS_PORT_NUMBER: 636
      # LDAP_TLS_CERT_FILE: /opt/bitnami/openldap/certs/openldap.crt
      # LDAP_TLS_KEY_FILE: /opt/bitnami/openldap/certs/openldap.key
      # LDAP_TLS_CA_FILE: /opt/bitnami/openldap/certs/openldapCA.crt
    volumes:
      - ./openldap:/bitnami/openldap
      # - /path/to/certs:/opt/bitnami/openldap/certs