version: '3.8'

services:
  auth-frontend:
    build:
      context: ../../auth-service/auth-frontend
      dockerfile: dev.Dockerfile

    volumes:
      - ../../auth-service/auth-frontend/app:/home/app
      - /home/app/node_modules
      - ../../.vscode-server/.vscode-auth-frontend:/root/.vscode-server

    labels:
      - "traefik.http.routers.auth-frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.auth-frontend.service=auth-frontend"
      - "traefik.http.routers.auth-frontend.entrypoints=web"
      - "traefik.http.services.auth-frontend.loadbalancer.server.port=80"


  auth-backend:
    build:
      context: ../../auth-service/auth-backend
      dockerfile: dev.Dockerfile
    env_file:
      - ../../auth-service/auth-backend/dev.env
    volumes:
      - ../../auth-service/auth-backend/src:/home/src
      - ../../.vscode-server.vscode-auth-backend:/root/.vscode-server

    
    labels:
      - "traefik.http.routers.auth-backend.rule=PathPrefix(`/auth/api`)"
      - "traefik.http.routers.auth-backend.service=auth-backend"
      - "traefik.http.routers.auth-backend.entrypoints=web"
      - "traefik.http.services.auth-backend.loadbalancer.server.port=8000"
    secrets:
      - all_db_user.txt
      - all_db_password.txt
      - email_app_password.json
  coredb: 
    image: mongo:5.0.9-focal
   
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/all_db_user.txt
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/all_db_password.txt

    secrets:
      - all_db_user.txt
      - all_db_password.txt
    
    volumes:
      - coredb-volume:/data/db

    ports:
      - 27017:27017

volumes:
  coredb-volume:

secrets:
  all_db_user.txt:
    file: ../../secret/dev/all_db_user.txt
  all_db_password.txt:
    file: ../../secret/dev/all_db_password.txt
  email_app_password.json:
    file: ../../secret/prod/email_app_password.json