version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --configFile=/root/.config/traefik.yaml
    labels:
      # This service is discoverable
      - traefik.http.services.traefik-traefik.loadBalancer.server.port=8080
      - traefik.enable=true
    ports:
      # The HTTP port
      - 2000:2000
      # The Web UI
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # For static config
      - ./config:/root/.config/
      # For logging
      - ./logs:/logs
      # For SSL
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - default

networks:
  default: