entryPoints:
  web-https:
    address: :2000
api:
  # This enable dashboard
  insecure: true
  dashboard: true
  debug: true
providers:
  docker:
    exposedByDefault: false # each container must set traefik.enable=true to get discovered
    network: traefik_default # the network these API is used
    defaultRule: Host(`{{.Name}}.localhost`)
    endpoint: unix:///var/run/docker.sock
  file:
    filename: /root/.config/tls.yaml # this is for SSL
accessLog:
  filePath: /logs/access.log
log:
  level: DEBUG
tracing:
  serviceName: api-fastapi